version: "3.9"
services:
  etcd:
    image: bitnami/etcd
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ENABLE_V2=true
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=default=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
    volumes:
      - ./.volumes/etcd:/bitnami/etcd
    # ports:
      # host_port:inter_container_port
      # - 5000:2379
      # - 5001:2380        

  # Like etcd-viewer
  etcdkeeper:
    image: evildecay/etcdkeeper
    container_name: etcdkeeper
    environment:
      - ETCD_PEER_ADDRESS=http://etcd:2379
      # - navigate to http://localhost:8080/etcdkeeper - and put host: etcd:2379 / etcd 2380
    ports:
      - 8080:8080
    
  server:
    # image: gilda-server
    build: backend/
    container_name: gilda-server
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_SERVICE_NAME=gilda-server
      - APPLICATION_SECRET=1234
    ports:
      - 8000:3000
    depends_on:
      - etcd


  # TODO: work in progress
  gilda-client:
    build: client/.
    container_name: gilda-client
    ports:
      - 5000:80
    # depends_on:
    #   - server
  
  gateway:
    container_name: gilda-gateway
    
    # build: gateway/
    image: bitnami/nginx:1.21.4-debian-10-r26
    volumes:
      - ./gateway/default.conf:/opt/bitnami/nginx/conf/server_blocks/gateway.conf

    ports:
      - 3000:80
    depends_on:
      - server
      - gilda-client