version: "3.9"
services:
  etcd:
    image: bitnami/etcd
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ENABLE_V2=true
      # - ETCD_NAME=feature_toggle_etcd
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=default=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
    volumes:
      - ./.volumes/etcd:/bitnami/etcd
    ports:
      - 5000:2379
      - 5001:2380        

  # Like etcd-viewer
  etcdkeeper:
    image: evildecay/etcdkeeper
    container_name: etcdkeeper
    environment:
      - ETCD_PEER_ADDRESS=http://etcd:5000
      # - navigate to http://localhost:8080/etcdkeeper - and put host: etcd:2379 / etcd 2380
    ports:
      - 8080:8080

  gateway:
    image: gilda-backend
    container_name: gilda-backend
    
  server:
    image: gilda-server
    container_name: gilda-server

  gilda-client:
    image: gilda-client
    container_name: gilda-client
    depends_on: 
      - server
  